[window]
padding = { x = 15, y = 15 }

[font]
normal = {family="SpaceMono Nerd Font Mono"}
bold = {family="SpaceMono Nerd Font Mono"}
italic = {family="SpaceMono Nerd Font Mono"}
bold_italic = {family="SpaceMono Nerd Font Mono"}
size = 13

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste"},
]

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.cache/material/alacritty.toml"
]
