#!/usr/bin/env bash

useCode=0
args=$@

if [[ "$@" == *"--code"* ]]; then
    useCode=1
    args=($(printf "%s\n" "$@" | grep -v -- '--code'))
    echo $args
fi
if [[ -n "$args" ]]; then
    selected=$args
else
    paths=$(find ~/Projects/ -mindepth 1 -maxdepth 1 -type d)
    paths+=$(printf "\n%s" "/home/aj/dotfiles")
    paths+=$(printf "\n%s" "create-new")
    selected=$(echo "$paths" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ $selected == "create-new" ]]; then
    echo "Enter new project name: "
    read project_name

    selected="/home/aj/Projects/$project_name"
    echo $selected
    mkdir $selected
fi

if [[ $useCode -eq 1 ]]; then
    code "$selected"
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
